-- AlterTable
ALTER TABLE "FlashSale" ADD COLUMN "maxUses" INTEGER;
ALTER TABLE "FlashSale" ADD COLUMN "usesCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "FlashSale" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;