import type { MetadataRoute } from "next";

/**
 * PWA Web App Manifest — generated by Next.js (overrides public/manifest.webmanifest).
 *
 * Enables "Add to Home Screen" on mobile and installable app behavior
 * on desktop. Icons from /public/icons/.
 */

export default function manifest(): MetadataRoute.Manifest {
  return {
    id: "/",
    name: "Aura Living — Considered Objects for the Considered Home",
    short_name: "Aura Living",
    description:
      "Premium home décor atelier. Handcrafted lamps, mirrors, planters, and sculptural objects. Warm minimalism, artisanal craft, made to be lived with.",
    start_url: "/?source=pwa",
    scope: "/",
    display: "standalone",
    orientation: "portrait-primary",
    background_color: "#FAF6EE",
    theme_color: "#0B0B0B",
    lang: "en",
    dir: "ltr",
    categories: ["shopping", "lifestyle", "home"],
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    shortcuts: [
      {
        name: "Shop",
        short_name: "Shop",
        description: "Browse all products",
        url: "/shop?source=pwa-shortcut",
        icons: [{ src: "/icons/icon-192.png", sizes: "192x192" }],
      },
      {
        name: "Journal",
        short_name: "Journal",
        description: "Read the Aura Living journal",
        url: "/journal?source=pwa-shortcut",
        icons: [{ src: "/icons/icon-192.png", sizes: "192x192" }],
      },
      {
        name: "Account",
        short_name: "Account",
        description: "View your account, orders, and wishlist",
        url: "/account?source=pwa-shortcut",
        icons: [{ src: "/icons/icon-192.png", sizes: "192x192" }],
      },
    ],
    prefer_related_applications: false,
  };
}
